In [1]:
import numpy as np
import matplotlib.pyplot as plt



In [2]:
# %load gallery
#! /usr/bin/env python3
#
def dif2_matrix ( n ):

  import numpy as np

  d = 2.0 * np.ones ( n )
  s = -1.0 * np.ones ( n - 1 )

  A = np.diag ( s, k = -1 ) + np.diag ( d ) + np.diag ( s, k = +1 )

  return A

def dif2_sparse ( n ):

  from scipy.sparse import spdiags
  from scipy.sparse import coo_matrix
  import numpy as np

  dm1 = -1.0 * np.ones ( n )
  dia = 2.0 * np.ones ( n )
  dp1 = -1.0 * np.ones ( n )
  data = np.array ( [ dm1, dia, dp1 ] )
  diags = np.array ( [ -1, 0, +1 ] )
  A = spdiags ( data, diags, n, n )
#
#  Convert to csc format.
#
  A = A.tocsc ( )

  return A

def frank_matrix ( n ):

  import numpy as np

  A = np.zeros ( [ n, n ], dtype = np.float )

  for i in range ( 0, n ):
    for j in range ( 0, n ):
      if ( j == i - 1 ):
        A[i,j] = float ( n - i )
      elif ( i <= j ):
        A[i,j] = float ( n - j )

  return A

def helmert_matrix ( n ):


  import numpy as np

  A = np.zeros ( ( n, n ), dtype = np.float )
#
#  A begins with the first row, diagonal, and lower triangle set to 1.
#
  for i in range ( 0, n ):
    for j in range ( 0, n ):

      if ( i == 0 ):
        A[i,j] = 1.0 / np.sqrt ( n )
      elif ( j < i ):
        A[i,j] = 1.0 / np.sqrt ( float ( i * ( i + 1 ) ) )
      elif ( i == j ):
        A[i,j] = float ( - i ) / np.sqrt ( float ( i * ( i + 1 ) ) )

  return A

def hilbert_inverse ( n ):

  import numpy as np

  A = np.zeros ( ( n, n ), dtype = np.float )
#
#  Set the (1,1) entry.
#
  A[0,0] = float ( n * n )
#
#  Define Row 1, Column J by recursion on Row 1 Column J-1
#
  i = 0
  for j in range ( 1, n ):
    A[i,j] = - A[i,j-1] * float ( ( n + j ) * ( i + j ) * ( n - j ) ) \
      / float ( ( i + j + 1 ) * j * j )
#
#  Define Row I by recursion on row I-1
#
  for i in range ( 1, n ):
    for j in range ( 0, n ):

      A[i,j] = - A[i-1,j] * float ( ( n + i ) * ( i + j ) * ( n- i ) ) \
        / float ( ( i + j + 1 ) * i * i )

  return A

def hilbert_matrix ( n ):

  import numpy as np

  A = np.zeros ( ( n, n ), dtype = np.float )

  for i in range ( 0, n ):
    for j in range ( 0 , n ):
      A[i,j] = 1.0 / float ( i + j + 1 )

  return A

def jordan_block ( n, alpha ):

  import numpy as np

  a = np.zeros ( ( n, n ) )

  for i in range ( 0, n ):
    for j in range ( 0, n ):

      if ( i == j ):
        a[i,j] = alpha
      elif ( j == i + 1 ):
        a[i,j] = 1.0

  return a

def lulu_matrix ( n = 5 ):

  import numpy as np

  A = np.array ( [ \
    [ -2,  1,  0,  0,  0 ], \
    [  1,  0,  1, -2,  0 ], \
    [  0,  0,  0,  1, -2 ], \
    [  1, -2,  1,  0,  0 ], \
    [  0,  1, -2,  1,  0 ] ], dtype = np.float )

  return A

def magic_matrix ( n ):

  import numpy as np

  n = int ( n )

  if ( n < 3 ):
    raise Exception ( "magic_matrix(): Size n must be at least 3!" )

  if ( n % 2 == 1 ):
    p = np.arange ( 1, n + 1 )
    A = n*np.mod(p[:, None] + p - (n+3)//2, n) + np.mod(p[:, None] + 2*p-2, n) + 1
  elif ( n % 4 == 0 ):
    J = np.mod(np.arange(1, n+1), 4) // 2
    K = J[:, None] == J
    A = np.arange(1, n*n+1, n)[:, None] + np.arange(n)
    A[K] = n*n + 1 - A[K]
  else:
    p = n // 2
    A = magic_matrix ( p )
    A = np.block([[A, A+2*p*p], [A+3*p*p, A+p*p]])
    i = np.arange(p)
    k = (n-2)//4
    j = np.concatenate((np.arange(k), np.arange(n-k+1, n)))
    A[np.ix_(np.concatenate((i, i+p)), j)] = A[np.ix_(np.concatenate((i+p, i)), j)]
    A[np.ix_([k, k+p], [0, k])] = A[np.ix_([k+p, k], [0, k])]

  A = A.astype ( float )

  return A 

def moler3_matrix ( n ):

  import numpy as np

  A = np.zeros ( ( n, n ), dtype = np.float )

  for i in range ( 0, n ):
    for j in range ( 0, n ):
      if ( i == j ):
        A[i,j] = float ( i + 1 )
      else:
        A[i,j] = float ( min ( i, j ) - 1 )

  return A

def pascal_matrix ( n ):

  import numpy as np

  A = np.zeros ( ( n, n ), dtype = np.float )

  for i in range ( 0, n ):
    for j in range ( 0, n ):

      if ( i == 0 ):
        A[i,j] = 1.0
      elif ( j == 0 ):
        A[i,j] = 1.0
      else:
        A[i,j] = A[i,j-1] + A[i-1,j]

  return A

def perm_matrix ( rows ):

  import numpy as np

  n = len ( rows )
  r1 = np.sort ( rows )
  r2 = np.arange ( n )
  if ( any ( r1 != r2 ) ):
    Exception ( 'perm_matrix(): input rows is not a permutation!' )
  A = np.zeros ( [ n, n ], dtype = np.float )
  for i in range ( 0, n ):
    A[i,rows[i]] = 1.0

  return A

def random_matrix ( n, seed = 123456789 ):

  import numpy as np

  np.random.seed ( seed )

  A = np.random.normal ( size = ( n, n ) )

  return A

if ( __name__ == '__main__' ):

  print ( "gallery:" )

  A = dif2_matrix ( 5 )
  print ( "" )
  print ( "dif2 matrix:" )
  print ( A )

  A = dif2_sparse ( 5 )
  print ( "" )
  print ( "dif2 sparse:" )
  print ( A )

  A = frank_matrix ( 5 )
  print ( "" )
  print ( "frank matrix:" )
  print ( A )

  A = helmert_matrix ( 5 )
  print ( "" )
  print ( "helmert matrix:" )
  print ( A )

  A = hilbert_matrix ( 5 )
  print ( "" )
  print ( "hilbert matrix:" )
  print ( A )

  A = hilbert_inverse ( 5 )
  print ( "" )
  print ( "hilbert inverse:" )
  print ( A )

  A = jordan_block ( 7, 0.5 )
  print ( "" )
  print ( "Jordan block:" )
  print ( A )

  A = magic_matrix ( 5 )
  print ( "" )
  print ( "magic matrix:" )
  print ( A )

  A = moler3_matrix ( 5 )
  print ( "" )
  print ( "moler3 matrix:" )
  print ( A )

  A = pascal_matrix ( 5 )
  print ( "" )
  print ( "pascal matrix:" )
  print ( A )

  A = perm_matrix ( [ 1, 3, 2, 0 ] )
  print ( "" )
  print ( "perm matrix:" )
  print ( A )

  A = random_matrix ( 5 )
  print ( "" )
  print ( "random matrix, default seed:" )
  print ( A )

  A = random_matrix ( 5, 1776 )
  print ( "" )
  print ( "random matrix, seed = 1776:" )
  print ( A )

  A = random_matrix ( 5 )
  print ( "" )
  print ( "random matrix, default seed:" )
  print ( A )



gallery:

dif2 matrix:
[[ 2. -1.  0.  0.  0.]
 [-1.  2. -1.  0.  0.]
 [ 0. -1.  2. -1.  0.]
 [ 0.  0. -1.  2. -1.]
 [ 0.  0.  0. -1.  2.]]

dif2 sparse:
  (1, 0)	-1.0
  (0, 0)	2.0
  (2, 1)	-1.0
  (1, 1)	2.0
  (0, 1)	-1.0
  (3, 2)	-1.0
  (2, 2)	2.0
  (1, 2)	-1.0
  (4, 3)	-1.0
  (3, 3)	2.0
  (2, 3)	-1.0
  (4, 4)	2.0
  (3, 4)	-1.0

frank matrix:
[[5. 4. 3. 2. 1.]
 [4. 4. 3. 2. 1.]
 [0. 3. 3. 2. 1.]
 [0. 0. 2. 2. 1.]
 [0. 0. 0. 1. 1.]]

helmert matrix:
[[ 0.4472136   0.4472136   0.4472136   0.4472136   0.4472136 ]
 [ 0.70710678 -0.70710678  0.          0.          0.        ]
 [ 0.40824829  0.40824829 -0.81649658  0.          0.        ]
 [ 0.28867513  0.28867513  0.28867513 -0.8660254   0.        ]
 [ 0.2236068   0.2236068   0.2236068   0.2236068  -0.89442719]]

hilbert matrix:
[[1.         0.5        0.33333333 0.25       0.2       ]
 [0.5        0.33333333 0.25       0.2        0.16666667]
 [0.33333333 0.25       0.2        0.16666667 0.14285714]
 [0.25       0.2        0.16666667 0.142

In [1]:
"""

import numpy as np
import matplotlib.pyplot as plt
from gallery import *

from time import time

#t1 = time ( )
#x = np.random.rand ( 10000 ) 
#xsq = np.power(x, 2)
#t2=time ( ) 
#dt = t2 - t1

# inverse
#np.linalg.inv(A)

def exercise1 ( n ) :
    import numpy as np
    import matplotlib.pyplot as plt
    import gallery 

    from time import time
    
    A = gallery.magic_matrix(n)
    b = np.ones(n)
    t1 = time()

    Ainv= np.linalg.inv(A)
    x = np.matmul(Ainv, b)
    t2 = time()

    dt = t2-t1
    return dt


dt = np.zeros(7)

n = [ 161, 321, 641, 1281, 2561, 5121, 10241 ]

for i in range(0, len(n)):
    dt[i] = exercise1(n[i])
    #print(dt[i])

for k in range(0, len(n)):
    print(n[k], dt[k], dt[k] / n[k]**3)
    
for k in range(0, len(n)-1):
    print(dt[k+1] / dt[k])"""

'\n\nimport numpy as np\nimport matplotlib.pyplot as plt\nfrom gallery import *\n\nfrom time import time\n\n#t1 = time ( )\n#x = np.random.rand ( 10000 ) \n#xsq = np.power(x, 2)\n#t2=time ( ) \n#dt = t2 - t1\n\n# inverse\n#np.linalg.inv(A)\n\ndef exercise1 ( n ) :\n    import numpy as np\n    import matplotlib.pyplot as plt\n    import gallery \n\n    from time import time\n    \n    A = gallery.magic_matrix(n)\n    b = np.ones(n)\n    t1 = time()\n\n    Ainv= np.linalg.inv(A)\n    x = np.matmul(Ainv, b)\n    t2 = time()\n\n    dt = t2-t1\n    return dt\n\n\ndt = np.zeros(7)\n\nn = [ 161, 321, 641, 1281, 2561, 5121, 10241 ]\n\nfor i in range(0, len(n)):\n    dt[i] = exercise1(n[i])\n    #print(dt[i])\n\nfor k in range(0, len(n)):\n    print(n[k], dt[k], dt[k] / n[k]**3)\n    \nfor k in range(0, len(n)-1):\n    print(dt[k+1] / dt[k])'

In [4]:

for k in range(0, len(n)):
    print(n[k], dt[k], dt[k] / n[k]**3)
for k in range(0, len(n)-1):
    print(dt[k+1] / dt[k])

161 0.006515026092529297 1.5611280650714144e-09
321 0.004940032958984375 1.4935327467369551e-10
641 0.016195058822631836 6.149055900711077e-11
1281 0.08497309684753418 4.0423513378078156e-11
2561 0.47637391090393066 2.836084938506226e-11
5121 3.5844979286193848 2.6690948434351485e-11
10241 0.0 0.0
0.7582522140086365
3.2783301158301157
5.246853239507118
5.606173348709186
7.524547097505226
0.0


In [5]:
#%%writefile exercise2.py

import numpy as np
import matplotlib.pyplot as plt
from gallery import *

from time import time

#t1 = time ( )
#x = np.random.rand ( 10000 ) 
#xsq = np.power(x, 2)
#t2=time ( ) 
#dt = t2 - t1

# inverse
#np.linalg.inv(A)

def exercise2 ( n ) :
    import numpy as np
    import matplotlib.pyplot as plt
    import gallery 

    from time import time
    
    A = gallery.magic_matrix(n)
    b = np.ones(n)
    t1 = time()

    #Ainv= np.linalg.inv(A)
    x = np.linalg.solve(A, b)
    t2 = time()

    dt = t2-t1
    return dt


dt = np.zeros(7)

n = [ 161, 321, 641, 1281, 2561, 5121, 10241 ]

for i in range(0, len(n)):
    dt[i] = exercise2(n[i])
    #print(dt[i])

for k in range(0, len(n)):
    print(n[k], dt[k], dt[k] / n[k]**3)
    
for k in range(0, len(n)-1):
    print(dt[k+1] / dt[k])


161 0.01630687713623047 3.9074476739597615e-09
321 0.003732919692993164 1.1285831185164337e-10
641 0.008869171142578125 3.3675104083273524e-11
1281 0.02707195281982422 1.2878704997023086e-11
2561 0.13539505004882812 8.06072401116897e-12
5121 0.8548579216003418 6.3654573551169145e-12
10241 7.410901784896851 6.899918472627875e-12
0.22891689572489618
2.3759340869898447
3.0523655913978494
5.001303413534364
6.313804834756149
8.669161971410674


In [6]:
def sparse_demo ( n ):
    from gallery import dif2_matrix , dif2_sparse 
    from scipy.sparse.linalg import spsolve
    import numpy as np
    A1= dif2_matrix ( n ) 
    A2= dif2_sparse ( n )
    b = np.ones ( n )
    
    x1 = np.linalg.solve ( A1, b ) 
    x2 = spsolve ( A2, b )

    print ( " n =", n, "||x1-x2|| =", np.linalg.norm ( x1-x2 ) )
    
sparse_demo(10)

 n = 10 ||x1-x2|| = 0.0


In [7]:
#%%writefile exercise3.py

import numpy as np
import matplotlib.pyplot as plt
#from gallery import *

from time import time

#t1 = time ( )
#x = np.random.rand ( 10000 ) 
#xsq = np.power(x, 2)
#t2=time ( ) 
#dt = t2 - t1

# inverse
#np.linalg.inv(A)

def exercise3 ( n ) :
    import numpy as np
    import matplotlib.pyplot as plt
    
    from scipy.sparse.linalg import spsolve
    from gallery import dif2_matrix , dif2_sparse 

    from time import time
    
    A = dif2_sparse(n)
    b = np.ones(n)
    t1 = time()

    #Ainv= np.linalg.inv(A)
    x = spsolve(A, b)
    t2 = time()

    dt = t2-t1
    return dt


dt = np.zeros(4)

n = [ 10000, 100000, 1000000, 10000000]

for i in range(0, len(n)):
    dt[i] = exercise3(n[i])
    #print(dt[i])

for k in range(0, len(n)):
    print(n[k], dt[k], dt[k] / n[k]**3)
    
for k in range(0, len(n)-1):
    print(dt[k+1] / dt[k])



10000 0.0032508373260498047 3.2508373260498045e-15
100000 0.029931068420410156 2.9931068420410153e-17
1000000 0.3398630619049072 3.3986306190490724e-19
10000000 4.690654039382935 4.6906540393829346e-21
9.207187385405208
11.354859009080771
13.80160001234664


In [8]:
#%%writefile exercise4.py

import numpy as np
import matplotlib.pyplot as plt
from gallery import dif2_matrix, frank_matrix, hilbert_matrix, pascal_matrix

from time import time

def exercise4 ( n, matrix ):
    import numpy as np
    import matplotlib.pyplot as plt
    
    from scipy.sparse.linalg import spsolve
    #from gallery import dif2_matrix , dif2_sparse 

    from time import time
    
    A = matrix ( n )
    d = np.linalg.det(A)
    c = np.linalg.cond(A)
    x1 = np.ones(n)
    
    b = np.matmul(A,x1)
    
    x2 = np.linalg.solve(A, b)
    
    e = np.linalg.norm(x1-x2) / np.linalg.norm(x1)
    #print("n =", n, "e =",e, "d =",d, "c =",c)
    print(n, e, d, c)
    return None

for matrix in [ dif2_matrix, frank_matrix, hilbert_matrix, pascal_matrix ]:
    for n in [ 5, 10, 15, 20,25 ]: 
        exercise4 ( n, matrix )

5 4.965068306494546e-17 6.0 13.92820323027552
10 3.510833468576701e-17 10.999999999999996 48.37415007870842
15 2.866583523299505e-17 15.999999999999984 103.08686891981762
20 3.933073774202345e-16 20.99999999999999 178.0642746108616
25 1.1282837789317048e-15 26.000000000000025 273.30605737670925
5 1.3527237254048918e-14 1.000000000000003 647.4683032841846
10 6.316830525625617e-11 0.9999999999808491 28543218.32668426
15 2.224354962283313e-05 0.9999908139649917 13710121106200.658
20 44.10798905845697 18.176616700513584 inf
25 11.514035490970816 237826221.14574957 6.718338316798195e+17
5 1.2638346025704821e-11 3.749295132515227e-12 476607.25024224253
10 0.00030059447258579624 2.1644052646213843e-53 16024909625167.58
15 2.6333981423148862 -2.1902999691192898e-120 3.378778714747708e+17
20 30.860877247847647 2.3721112576915098e-195 1.5315755993591903e+18
25 126.45110075201403 -4.362825574548375e-272 1.7790685999264205e+18
5 0.0 0.9999999999999998 8517.524361138385
10 1.210002225048495e-07 0.9

In [9]:
#%%writefile lu_factor.py

def lu_factor ( A ): 
    import numpy as np
    import matplotlib.pyplot as plt
    
    from scipy.sparse.linalg import spsolve
    #from gallery import dif2_matrix , dif2_sparse 

    from time import time
    
    n = A.shape[0]
   
    L = np.eye ( n )
    U = np.copy(A)
    for j in range(0,n-1):
        for i in range( j+1 , n):
            if ( U[j,j] == 0.0 ):
                raise Exception ( ' lu_factor : Divisor Ujj is 0! ')
            L[i,j] = U[i, j] /U[j,j]
            U[i,j:n]=U[i,j:n] - L[i,j] * U[j,j:n]
            #print(j,i,U, L)
    return L, U





In [10]:

#%%writefile exercise5.py

import numpy as np
import matplotlib.pyplot as plt
from gallery import dif2_matrix, frank_matrix, hilbert_matrix, pascal_matrix
from lu_factor import lu_factor
from time import time

n = 5
A = hilbert_matrix(n)

L, U = lu_factor ( A )    

LU = np.matmul(L,U)
e = np.linalg.norm(A - LU)
print(e)

5.551115123125783e-17


In [11]:
#%%writefile exercise6.py

import numpy as np
import matplotlib.pyplot as plt
from gallery import dif2_matrix, frank_matrix, hilbert_matrix, pascal_matrix, lulu_matrix
from lu_factor import lu_factor
from time import time

from scipy.linalg import lu

n = 5
A = lulu_matrix()

d = np.linalg.det(A)
c = np.linalg.cond(A)
print(d,c)


#e = np.linalg.norm(x1-x2) / np.linalg.norm(x1)
#L, U = lu_factor ( A )    

#LU = np.matmul(L,U)
#e = np.linalg.norm(A - LU)
try :
    L,U = lu_factor (A) 
except ( Exception ) :
    print ( " lu_factor() failed for this matrix!" )

P, L, U = lu ( A )

LU = np.matmul(L,U)
PLU = np.matmul(P, LU)
e = np.linalg.norm(A - PLU)
print(e)



-8.000000000000002 15.40034052046508
 lu_factor() failed for this matrix!
0.0


In [12]:
#%%writefile exercise7.py

import numpy as np
import matplotlib.pyplot as plt
from gallery import magic_matrix, perm_matrix
from lu_factor import lu_factor
from time import time

from scipy.linalg import lu

A = magic_matrix(4)

#P1 = np.array([[1,0,0,0], [0,0,1,0], [0,1,0,0], [0,0,0,1]])
P1 = perm_matrix ( [ 0, 2, 1, 3 ] )
P2 = perm_matrix ( [ 0, 3, 2, 1 ] )

P1A = np.matmul(P1, A)
P1TP1A = np.matmul(np.transpose(P1), P1A)
P1TP1 = np.matmul(np.transpose(P1), P1)
AP1 = np.matmul(A,P1)
P1P2 = np.matmul(P1, P2)
P1P2A = np.matmul(P1P2, A)


In [13]:
#%%writefile plu_factor.py

def plu_factor ( A ): 
    import numpy as np
    import matplotlib.pyplot as plt
    
    from scipy.sparse.linalg import spsolve
    #from gallery import dif2_matrix , dif2_sparse 

    from time import time
    
    n = A.shape[0]
    
    P = np.eye(n)
    L = np.eye( n )
    U = np.copy(A)
    
    for j in range(0,n-1):
        p = np.argmax(np.abs(U[j:n, j]))
        if (p != 0):
            p = p+j
            U[[j,p],:] =U[[p,j],:] 
            L[[j,p],0:j] = L[[p,j],0:j]
            P[:,[j,p]] =P[:,[p,j]]
        for i in range( j+1 , n):
            #if ( U[j,j] == 0.0 ):
                #raise Exception ( ' lu_factor : Divisor Ujj is 0! ')
            L[i,j] = U[i, j] /U[j,j]
            U[i,j:n]=U[i,j:n] - L[i,j] * U[j,j:n]
            #print(j,i,U, L)
    return P, L, U

In [14]:
n = 5
A = lulu_matrix()
P, L, U =plu_factor ( A )
P,L,U
LU = np.matmul(L,U)
PLU = np.matmul(P,LU)
PLU, A

(array([[-2.,  1.,  0.,  0.,  0.],
        [ 1.,  0.,  1., -2.,  0.],
        [ 0.,  0.,  0.,  1., -2.],
        [ 1., -2.,  1.,  0.,  0.],
        [ 0.,  1., -2.,  1.,  0.]]),
 array([[-2.,  1.,  0.,  0.,  0.],
        [ 1.,  0.,  1., -2.,  0.],
        [ 0.,  0.,  0.,  1., -2.],
        [ 1., -2.,  1.,  0.,  0.],
        [ 0.,  1., -2.,  1.,  0.]]))

In [15]:
#%%writefile exercise8.py

import numpy as np
import matplotlib.pyplot as plt

from time import time

from scipy.linalg import lu
from gallery import dif2_matrix, pascal_matrix, lulu_matrix
from lu_factor import lu_factor
from plu_factor import plu_factor


matrix = [dif2_matrix, pascal_matrix, lulu_matrix]

n=5

for mat in matrix:
    A = mat(5)
    P,L,U = plu_factor(A) 
    LU = np.matmul(L,U)
    PLU = np.matmul(P,LU)
    e = np.linalg.norm(A - PLU)
    print(e)

0.0
0.0
0.0


In [32]:
#%%writefile plu_solve.py


def p_solve ( P, b ): 
    import numpy as np
    import matplotlib.pyplot as plt

    from time import time

    from lu_factor import lu_factor
    from plu_factor import plu_factor

    PT = np.transpose(P)
    z = np.matmul(PT, b)
    return z


def l_solve ( L, z ): 
    import numpy as np
    import matplotlib.pyplot as plt

    from time import time

    from lu_factor import lu_factor
    from plu_factor import plu_factor

    n = len(z)
    y = z.copy()
    for i in range(0, n):
        for j in range(0, i):
            y[i] = y[i] - L[i,j] * y[j]
    return y


def u_solve ( U, y ): 
    import numpy as np
    import matplotlib.pyplot as plt

    from time import time

    from lu_factor import lu_factor
    from plu_factor import plu_factor

    n = len(y)
    x = y.copy()
    
    # error???? 
    #for i in range(n-1, -1, -1):
        #for j in range(i-1, -1,-1):
         #   x[i] = x[i] - U[i,j] * x[j]
    #  x[i] = x[i]/U[i,i]

    for i in range(0, n):
        for j in range(0, i):
            x[n-1 - i] = x[n-1-i] - U[n-1-i,n-1-j] * x[n-1-j]
        x[n-1- i] = x[n-1-i]/U[n-1-i, n-1-i]
    
    
    return x



In [29]:
U = np.array([[4,4,8], [0,4,8], [0,0,2]])
y = np.array([16,20,4])
x =  u_solve ( U, y )
x
#x2 = np.linalg.solve(U,y)
#x,x2

array([-1,  1,  2])

In [19]:
#%%writefile exercise9.py
import numpy as np
import matplotlib.pyplot as plt

from time import time

from scipy.linalg import lu
from gallery import dif2_matrix, pascal_matrix, lulu_matrix
from lu_factor import lu_factor
from plu_factor import plu_factor

from plu_solve import *


A = np.array([[2,6,12], [1,3,8], [4,4,8]])
b = np.array([28,18,16])

P, L, U  = plu_factor(A)

z = p_solve ( P, b )
y = l_solve ( L, z )
x =  u_solve ( U, y )
Ax = np.matmul(A,x)

e = np.linalg.norm(Ax - b)
e

52.354560450833695

array([4, 5, 2])